// =================================================================================
// This is auto-generated by the GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package leave

import (
	"context"

	"hinay.cn/admin/api/leave/v1"
)

type ILeaveV1 interface {
	LeaveList(ctx context.Context, req *v1.LeaveListReq) (res *v1.LeaveListRes, err error)
	LeaveCreate(ctx context.Context, req *v1.LeaveCreateReq) (res *v1.LeaveCreateRes, err error)
	LeaveUpdate(ctx context.Context, req *v1.LeaveUpdateReq) (res *v1.LeaveUpdateRes, err error)
	LeaveDelete(ctx context.Context, req *v1.LeaveDeleteReq) (res *v1.LeaveDeleteRes, err error)
	LeaveSubmit(ctx context.Context, req *v1.LeaveSubmitReq) (res *v1.LeaveSubmitRes, err error)
	LeaveCancel(ctx context.Context, req *v1.LeaveCancelReq) (res *v1.LeaveCancelRes, err error)
}
