// =================================================================================
// This is auto-generated by the GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package ai

import (
	"context"

	"hinay.cn/admin/api/ai/v1"
)

type IAiV1 interface {
	AiChat(ctx context.Context, req *v1.AiChatReq) (res *v1.AiChatRes, err error)
	AiConfig(ctx context.Context, req *v1.AiConfigReq) (res *v1.AiConfigRes, err error)
	AiHistory(ctx context.Context, req *v1.AiHistoryReq) (res *v1.AiHistoryRes, err error)
	AiSessions(ctx context.Context, req *v1.AiSessionsReq) (res *v1.AiSessionsRes, err error)
	AiSessionDelete(ctx context.Context, req *v1.AiSessionDeleteReq) (res *v1.AiSessionDeleteRes, err error)
}
