// =================================================================================
// This is auto-generated by the GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package ai

import (
	"hinay.cn/admin/api/ai"
)

type ControllerV1 struct{}

func NewV1() ai.IAiV1 {
	return &ControllerV1{}
}
