// =================================================================================
// This is auto-generated by the GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package post

import (
	"context"

	"hinay.cn/admin/api/post/v1"
)

type IPostV1 interface {
	PostList(ctx context.Context, req *v1.PostListReq) (res *v1.PostListRes, err error)
	PostAll(ctx context.Context, req *v1.PostAllReq) (res *v1.PostAllRes, err error)
	PostCreate(ctx context.Context, req *v1.PostCreateReq) (res *v1.PostCreateRes, err error)
	PostUpdate(ctx context.Context, req *v1.PostUpdateReq) (res *v1.PostUpdateRes, err error)
	PostDelete(ctx context.Context, req *v1.PostDeleteReq) (res *v1.PostDeleteRes, err error)
	PostMemberList(ctx context.Context, req *v1.PostMemberListReq) (res *v1.PostMemberListRes, err error)
	PostMemberAdd(ctx context.Context, req *v1.PostMemberAddReq) (res *v1.PostMemberAddRes, err error)
	PostMemberRemove(ctx context.Context, req *v1.PostMemberRemoveReq) (res *v1.PostMemberRemoveRes, err error)
}
