// =================================================================================
// This is auto-generated by the GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package post

import (
	"hinay.cn/admin/api/post"
)

type ControllerV1 struct{}

func NewV1() post.IPostV1 {
	return &ControllerV1{}
}
