// =================================================================================
// This is auto-generated by the GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package flow

import (
	"hinay.cn/admin/api/flow"
)

type ControllerV1 struct{}

func NewV1() flow.IFlowV1 {
	return &ControllerV1{}
}
