// =================================================================================
// This is auto-generated by the GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package flow

import (
	"context"

	"hinay.cn/admin/api/flow/v1"
)

type IFlowV1 interface {
	DefinitionList(ctx context.Context, req *v1.FlowDefinitionListReq) (res *v1.FlowDefinitionListRes, err error)
	DefinitionUsable(ctx context.Context, req *v1.FlowDefinitionUsableReq) (res *v1.FlowDefinitionUsableRes, err error)
	DefinitionDetail(ctx context.Context, req *v1.FlowDefinitionDetailReq) (res *v1.FlowDefinitionDetailRes, err error)
	DefinitionCreate(ctx context.Context, req *v1.FlowDefinitionCreateReq) (res *v1.FlowDefinitionCreateRes, err error)
	DefinitionUpdate(ctx context.Context, req *v1.FlowDefinitionUpdateReq) (res *v1.FlowDefinitionUpdateRes, err error)
	DefinitionDelete(ctx context.Context, req *v1.FlowDefinitionDeleteReq) (res *v1.FlowDefinitionDeleteRes, err error)
	DefinitionPublish(ctx context.Context, req *v1.FlowDefinitionPublishReq) (res *v1.FlowDefinitionPublishRes, err error)
	DefinitionDisable(ctx context.Context, req *v1.FlowDefinitionDisableReq) (res *v1.FlowDefinitionDisableRes, err error)
	DesignerOptions(ctx context.Context, req *v1.FlowDesignerOptionsReq) (res *v1.FlowDesignerOptionsRes, err error)
	InstanceStart(ctx context.Context, req *v1.FlowInstanceStartReq) (res *v1.FlowInstanceStartRes, err error)
	InstanceList(ctx context.Context, req *v1.FlowInstanceListReq) (res *v1.FlowInstanceListRes, err error)
	InstanceDetail(ctx context.Context, req *v1.FlowInstanceDetailReq) (res *v1.FlowInstanceDetailRes, err error)
	InstanceCancel(ctx context.Context, req *v1.FlowInstanceCancelReq) (res *v1.FlowInstanceCancelRes, err error)
	InstanceResubmit(ctx context.Context, req *v1.FlowInstanceResubmitReq) (res *v1.FlowInstanceResubmitRes, err error)
	TaskApprove(ctx context.Context, req *v1.FlowTaskApproveReq) (res *v1.FlowTaskApproveRes, err error)
	TaskReject(ctx context.Context, req *v1.FlowTaskRejectReq) (res *v1.FlowTaskRejectRes, err error)
	TaskRead(ctx context.Context, req *v1.FlowTaskReadReq) (res *v1.FlowTaskReadRes, err error)
	TaskCount(ctx context.Context, req *v1.FlowTaskCountReq) (res *v1.FlowTaskCountRes, err error)
}
