// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hinay.cn/admin/internal/dao/internal"
)

// aiChatMessageDao is the data access object for the table ai_chat_message.
// You can define custom methods on it to extend its functionality as needed.
type aiChatMessageDao struct {
	*internal.AiChatMessageDao
}

var (
	// AiChatMessage is a globally accessible object for table ai_chat_message operations.
	AiChatMessage = aiChatMessageDao{internal.NewAiChatMessageDao()}
)

// Add your custom methods and functionality below.
