// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hinay.cn/admin/internal/dao/internal"
)

// aiConversationDao is the data access object for the table ai_conversation.
// You can define custom methods on it to extend its functionality as needed.
type aiConversationDao struct {
	*internal.AiConversationDao
}

var (
	// AiConversation is a globally accessible object for table ai_conversation operations.
	AiConversation = aiConversationDao{internal.NewAiConversationDao()}
)

// Add your custom methods and functionality below.
