// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hinay.cn/admin/internal/dao/internal"
)

// bizMessageDao is the data access object for the table biz_message.
// You can define custom methods on it to extend its functionality as needed.
type bizMessageDao struct {
	*internal.BizMessageDao
}

var (
	// BizMessage is a globally accessible object for table biz_message operations.
	BizMessage = bizMessageDao{internal.NewBizMessageDao()}
)

// Add your custom methods and functionality below.
