// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hinay.cn/admin/internal/dao/internal"
)

// bizMessageTargetDao is the data access object for the table biz_message_target.
// You can define custom methods on it to extend its functionality as needed.
type bizMessageTargetDao struct {
	*internal.BizMessageTargetDao
}

var (
	// BizMessageTarget is a globally accessible object for table biz_message_target operations.
	BizMessageTarget = bizMessageTargetDao{internal.NewBizMessageTargetDao()}
)

// Add your custom methods and functionality below.
