// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hinay.cn/admin/internal/dao/internal"
)

// bizMessageReadDao is the data access object for the table biz_message_read.
// You can define custom methods on it to extend its functionality as needed.
type bizMessageReadDao struct {
	*internal.BizMessageReadDao
}

var (
	// BizMessageRead is a globally accessible object for table biz_message_read operations.
	BizMessageRead = bizMessageReadDao{internal.NewBizMessageReadDao()}
)

// Add your custom methods and functionality below.
