// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hinay.cn/admin/internal/dao/internal"
)

// bizLeaveDao is the data access object for the table biz_leave.
// You can define custom methods on it to extend its functionality as needed.
type bizLeaveDao struct {
	*internal.BizLeaveDao
}

var (
	// BizLeave is a globally accessible object for table biz_leave operations.
	BizLeave = bizLeaveDao{internal.NewBizLeaveDao()}
)

// Add your custom methods and functionality below.
