// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hinay.cn/admin/internal/dao/internal"
)

// sysUserTotpDao is the data access object for the table sys_user_totp.
// You can define custom methods on it to extend its functionality as needed.
type sysUserTotpDao struct {
	*internal.SysUserTotpDao
}

var (
	// SysUserTotp is a globally accessible object for table sys_user_totp operations.
	SysUserTotp = sysUserTotpDao{internal.NewSysUserTotpDao()}
)

// Add your custom methods and functionality below.
