// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hinay.cn/admin/internal/dao/internal"
)

// sysApiDao is the data access object for the table sys_api.
// You can define custom methods on it to extend its functionality as needed.
type sysApiDao struct {
	*internal.SysApiDao
}

var (
	// SysApi is a globally accessible object for table sys_api operations.
	SysApi = sysApiDao{internal.NewSysApiDao()}
)

// Add your custom methods and functionality below.
