// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hinay.cn/admin/internal/dao/internal"
)

// sysRoleOrgDao is the data access object for the table sys_role_org.
// You can define custom methods on it to extend its functionality as needed.
type sysRoleOrgDao struct {
	*internal.SysRoleOrgDao
}

var (
	// SysRoleOrg is a globally accessible object for table sys_role_org operations.
	SysRoleOrg = sysRoleOrgDao{internal.NewSysRoleOrgDao()}
)

// Add your custom methods and functionality below.
