// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hinay.cn/admin/internal/dao/internal"
)

// sysAuditLogDao is the data access object for the table sys_audit_log.
// You can define custom methods on it to extend its functionality as needed.
type sysAuditLogDao struct {
	*internal.SysAuditLogDao
}

var (
	// SysAuditLog is a globally accessible object for table sys_audit_log operations.
	SysAuditLog = sysAuditLogDao{internal.NewSysAuditLogDao()}
)

// Add your custom methods and functionality below.
