// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hinay.cn/admin/internal/dao/internal"
)

// sysOrgDao is the data access object for the table sys_org.
type sysOrgDao struct {
	*internal.SysOrgDao
}

var (
	// SysOrg is a globally accessible object for table sys_org operations.
	SysOrg = sysOrgDao{internal.NewSysOrgDao()}
)

// Add your custom methods and functionality below.
