// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hinay.cn/admin/internal/dao/internal"
)

// wfDefinitionDao is the data access object for the table wf_definition.
// You can define custom methods on it to extend its functionality as needed.
type wfDefinitionDao struct {
	*internal.WfDefinitionDao
}

var (
	// WfDefinition is a globally accessible object for table wf_definition operations.
	WfDefinition = wfDefinitionDao{internal.NewWfDefinitionDao()}
)

// Add your custom methods and functionality below.
