// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hinay.cn/admin/internal/dao/internal"
)

// wfInstanceDao is the data access object for the table wf_instance.
// You can define custom methods on it to extend its functionality as needed.
type wfInstanceDao struct {
	*internal.WfInstanceDao
}

var (
	// WfInstance is a globally accessible object for table wf_instance operations.
	WfInstance = wfInstanceDao{internal.NewWfInstanceDao()}
)

// Add your custom methods and functionality below.
