// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hinay.cn/admin/internal/dao/internal"
)

// wfRecordDao is the data access object for the table wf_record.
// You can define custom methods on it to extend its functionality as needed.
type wfRecordDao struct {
	*internal.WfRecordDao
}

var (
	// WfRecord is a globally accessible object for table wf_record operations.
	WfRecord = wfRecordDao{internal.NewWfRecordDao()}
)

// Add your custom methods and functionality below.
