// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hinay.cn/admin/internal/dao/internal"
)

// wfTaskDao is the data access object for the table wf_task.
// You can define custom methods on it to extend its functionality as needed.
type wfTaskDao struct {
	*internal.WfTaskDao
}

var (
	// WfTask is a globally accessible object for table wf_task operations.
	WfTask = wfTaskDao{internal.NewWfTaskDao()}
)

// Add your custom methods and functionality below.
