// =================================================================================
// This is auto-generated by the GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package leave

import (
	"hinay.cn/admin/api/leave"
)

type ControllerV1 struct{}

func NewV1() leave.ILeaveV1 {
	return &ControllerV1{}
}
